### PR TITLE
Download data for a report over multiple days

### PR DESCRIPTION
**Pull request by gorel**
There are probably over a thousand optimizations you could make for this code, but as of right now, this at least _works_, and I don't see any glaring errors.

Since we didn't have an index on FieldData.ds, this runs very slowly. Adding the index should help immensely, but I'm still leery of how well this works.

At any rate, I can say this is functional, at least.

### CODE REVIEW

**Comment by ad08fee3** [comment]
Getting an error when trying to download.
I figured it was the database being out of date, so I dropped and ran create_db again. Still getting the same error.

**Comment by gorel** [comment]
Still working on this. This patch keeps getting merge conflicts.

**Comment by gorel** [comment]
MERGE CONFLICTS ARE YOU F***ING KIDDING ME

**Pull request merged**
