### PR TITLE
Fixes #150

### LINKED ISSUE #150: Create chart -> no include table -> table only
= no data
= sad

### PR DESCRIPTION
**Pull request by gorel**
Also changing imports to an easier to read (and lint-check) style.

### CODE REVIEW

**Comment by gorel** [comment]
Also, by inheriting from flask_login.UserMixin, is_active(), is_authenticated(), and get_id() can be automatically inherited.

**Comment by gorel** [comment]
I need to fix this still

**Comment by ad08fee3** [comment]
What exactly does this do? (What should I be testing for?)

**Comment by gorel** [comment]
Try to create a chart that either:
- has no fields selected (expected result: error message)
- is of type "table only", but doesn't select the "with table" box (in this case, the with table box is implied, and a table only chart should be created)

**Comment by ad08fee3** [comment]
When I try to make a table with no fields I get:
NameError: global name 'ChartTypeConstants' is not defined

~~Should I update the database?~~

create_db doesn't fix the issue.

**Comment by gorel** [comment]
Huh, that's weird. I'll take a look at it. Don't merge for now.

**Comment by ad08fee3** [comment]
Update: You get that error every time you _don't_ include a table. If you include the table it works fine.

Selecting "Include table" with no fields selected gives you the appropriate "You've created an empty chart!"  error. But if you don't include the table, no matter what, you get the ChartTypeConstants error.

**Comment by ad08fee3** [comment]
If you select "TABLE ONLY" but not "Include table?" then it creates successfully with a table.
I believe this is desired output, right?
If so, LGTM

**Comment by gorel** [comment]
Correct, that's our desired behavior. Merging, then.

**Pull request merged**
