### PR TITLE
Admin control panel

### PR DESCRIPTION
**Pull request by gorel**

### CODE REVIEW

**Comment by ad08fee3** [comment]
Needs fixed:
=Edit_departments:
    ---Button needs to say Department, not Location
    ---Nothing actually gets added
=Edit_fields:
    ---"Department: Not a valid choice" why?
    ---Should my field type be blank?
=Edit_locations:
    ---Nothing actually gets added
=Edit_users:
    ---There should be a reset password button by each user
    ---Adding new user gives errors: "Email: Emails must match" (there is only one field) and Confirm "Email: Please confirm your email address." (Does that just get shown when it sends an email?)

Besides usability, it looks good to me. Idk if those usability issues are part of this branch. I feel like they should be separate. Some of those issues need fixed (e.g. "Emails must match")

**Comment by gorel** [comment]
That's what I get for committing something based on looks and not functionality....
I'll take a look. Thanks for the feedback.

Come chill at my place if you want. lol

**Comment by ad08fee3** [comment]
Also, a reset-password button should be added next to each user on the edit users page.

Question: Will the admins be able to edit user's information? That's not in Waffles. Or can they just delete/password reset?

**Comment by gorel** [comment]
Not in waffles = not our responsibility.

Which makes sense... Why should an admin be able to change your name? lol

**Comment by ad08fee3** [comment]
I'm not saying he should, I just didn't know if that's something we wanted to add or not

**Comment by ad08fee3** [comment]
Just make it so "confirm email" fields are checked without case. jim@yahoo should == JIM@YAHoO

After that, LGTM

**Pull request merged**
