### PR TITLE
More info about RegisterCandidates

### PR DESCRIPTION
**Pull request by gorel**
LOOK AT THIS AMAZING FEATURE!

### CODE REVIEW

**Comment by gorel** [comment]
register_time
HERE IT IS IN PRODUCTION!

**Comment by ad08fee3** [comment]
mod_admin forms.py --> we ain't a school bruh
mod_auth models.py --> candidate not defined, Message not defined

**Comment by mozilla2012** [comment]
LGTM

**Comment by ad08fee3** [comment]
LGTM
small3

**Pull request merged**
